#!/bin/bash

###############################################
#author: deepti Hegde
#Date-11/01/2026
#This script is used to monitor system health

#version: 0.0.1
##############################################
# this is main 
echo "System uptime:"
uptime

echo "Memory usage"
free -h

echo "Disk usage"
df -h

echo "number of CPU's"
nproc
