#!/bin/bash

###############################################
#author: deepti Hegde
#Date-11/01/2026
#This script is used to monitor system health

#version: 0.0.2
##############################################

set -x 
set -e
set -o pipefail
echo "System health log"
echo "Date :$(date)" >> health.log
echo "System uptime:$(uptime -p)" >> health.log

echo "Memory usage:$(free -h)" >> health.log

echo "Disk usage :$(df -h)" >> health.log

echo "number of CPU's:$(nproc)" >> health.log

diskusage=$( df -h / | tail -1 | awk -F" " '{print $5}' | sed 's/%//' )
if [ $diskusage -gt 80 ]
then 
    echo "disk usage is greater than 80%" >> health.log
else
    echo "disk usage is in control" >> health.log
fi
